first_name = input("Enter first name: ")
last_name = input("Enter last name: ")
email_address= input("Enter email address: ")
age = int(input("Enter age: "))
height = float(input("Enter height in inches: "))
weight = float(input("Enter weight in pounds: "))
BMI = (703 * weight)/(height*height)
print("Name:", first_name, last_name)
print("Email Address:", email_address)
print("Age:", age)
print("Height:", height)
print("Weight:", weight)
print("BMI:", BMI)
